jobs:
  - name: external-ci-users-pr
    plan:
      - get: external-ci-users-pr
        trigger: true
        version: every
      - put: external-ci-users-pr
        params:
          path: external-ci-users-pr
          status: pending
        input_mapping:
          external-ci-users: external-ci-users-pr
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          external-ci-users: external-ci-users-pr
      - .: (( inject meta.plan.terraform-plan ))
        input_mapping:
          external-ci-users: external-ci-users-pr
        params:
          TF_WORKSPACE: 'qa'
          DETAILED_EXITCODE: ''
        on_failure:
          put: external-ci-users-pr
          params:
            path: external-ci-users-pr
            status: failure
        on_success:
          put: external-ci-users-pr
          params:
            path: external-ci-users-pr
            status: success
